- name: Create kops cluster
  gather_facts: false
  hosts: "{{ host_group }}"

- name: Create Namespace
  k8s:
    state: present
    definition:
      kind: Namespace
      apiVersion: v1
      metadata:
        name: my-namespace

- name: Deploy My Helm Chart
  helm:
    name: my-app
    chart: ./path/to/my-chart
    namespace: my-namespace
    values_files:
      - path/to/my-values.yaml