controller:
  ingressClass: alb
  config:
    use-forwarded-headers: "true"
    use-proxy-protocol: "true"
  service:
    enabled: true
    annotations:
      "service.beta.kubernetes.io/aws-load-balancer-type": "alb"