controller:
  replicaCount: 1  # Adjust as needed
  config:
    use-forwarded-headers: "true"
    use-proxy-protocol: "true"
  publishService:
    enabled: true
  admissionWebhooks:
    enabled: false  # Set to true if you want to enable admission webhooks
