- name: Set git directory remote url with token
  gather_facts: true
  hosts: "{{ host_group }}"

  tasks:

    - name: Get Git user name
      command: git config --global user.name
      register: git_user_name
      ignore_errors: yes

    - name: Set Git user name and email if not configured
      git_config:
        name: user.name
        value: "{{ GIT_USER_NAME }}"
        scope: global
      when: git_user_name.rc != 0

    - name: Get Git user email
      command: git config --global user.email
      register: git_user_email
      ignore_errors: yes

    - name: Set Git user email if not configured
      git_config:
        name: user.email
        value: "{{ GIT_USER_EMAIL }}"
        scope: global
      when: git_user_email.rc != 0

    - name: Create Git local directory
      file:
        path: "{{ GIT_LOCAL_DIR }}"
        state: directory

    - name: Check if .git directory exists in Git local directory
      stat:
        path: "{{ GIT_LOCAL_DIR }}/.git"
      register: git_directory_exists

    - name: Set Git
      args:
        chdir: "{{ GIT_LOCAL_DIR }}"
        executable: /bin/bash
      shell: |
        git init
        git branch -M "{{ GIT_BRANCH_NAME }}"
        git remote add "{{ GIT_LOCAL_REMOTE_NAME }}" "{{ GIT_REPO_URL }}"
        git remote set-url "{{ GIT_LOCAL_REMOTE_NAME }}" "{{ GIT_REPO_AUTH_URL }}"
        git push "{{ GIT_LOCAL_REMOTE_NAME }}" "{{ GIT_BRANCH_NAME }}"
      when: git_directory_exists.stat.exists == false

    - name: Check Git remote URL
      git_config:
        repo: "{{ GIT_LOCAL_DIR }}"  # Replace with the path to your repository
        name: remote.{{ GIT_LOCAL_REMOTE_NAME }}.url
      register: git_remote_repo_url
      when: git_directory_exists.stat.exists == true

    - name: Merge Git repository when remote_url is already defined
      args:
        chdir: "{{ GIT_LOCAL_DIR }}"
        executable: /bin/bash
      shell: |
        git branch -M "{{ GIT_BRANCH_NAME }}"
        git add .
        git commit -m "{{ GIT_COMMIT_MESSAGE }}"
        git push "{{ GIT_LOCAL_REMOTE_NAME }}" "{{ GIT_BRANCH_NAME }}"
      when: git_directory_exists.stat.exists == true and git_remote_repo_url.value is defined

    - name: Merge Git repository when remote_url is not defined yet
      args:
        chdir: "{{ GIT_LOCAL_DIR }}"
        executable: /bin/bash
      shell: |
        git remote add "{{ GIT_LOCAL_REMOTE_NAME }}" "{{ GIT_REPO_URL }}"
        git remote set-url "{{ GIT_LOCAL_REMOTE_NAME }}" "{{ GIT_REPO_AUTH_URL }}"
        git branch -M "{{ GIT_BRANCH_NAME }}"
        git add .
        git commit -m "{{ GIT_COMMIT_MESSAGE }}"
        git push "{{ GIT_LOCAL_REMOTE_NAME }}" "{{ GIT_BRANCH_NAME }}"
      when: git_directory_exists.stat.exists == true and git_remote_repo_url.value is not defined