- name: Create Helm Chart
  gather_facts: false
  hosts: "{{ host_group }}"

  tasks:

  - name: Create Namespace
    k8s:
      state: present
      definition:
        kind: Namespace
        apiVersion: v1
        metadata:
          name: helm

  - name: Deploy My Helm Chart
    helm:
      name: my-app
      chart: ./path/to/my-chart
      namespace: helm
      values_files:
        - path/to/my-values.yaml