#!/bin/bash
GIT_OWNER=$GIT_OWNER
GIT_REPO=$GIT_REPO
SECRET_DATA_DIR=$SECRET_DATA_DIR

SCRIPT_DIR="$(dirname "$0")"
SECRET_DATA_DIR="$SCRIPT_DIR/$SECRET_DATA_DIR"

for SECRET_DATA_FILE in "$SECRET_DATA_DIR"/*
do
    SECRET_DATA=$(cat "$SECRET_DATA_FILE")
    
    SECRET_DATA_FILE_NAME=$(basename "$SECRET_DATA_FILE")
    SECRET_DATA_FILE_PURE_NAME="${SECRET_DATA_FILE_NAME%.*}"

    gh secret set "$SECRET_DATA_FILE_PURE_NAME" --repo "$GIT_OWNER/$GIT_REPO" --body "$SECRET_DATA"
done