- name: Install AWS cli
  gather_facts: true
  collections:
    - community.general
  hosts: "{{ host_group }}"
  
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    playbook_file_path: "{{ (lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ')).split() | select('match','^.*[.]ya?ml$') | list | first }}"
    playbook_dir_path: "{{ playbook_file_path | dirname }}"
    playbook_file_name: "{{ playbook_file_path | basename }}"

  tasks:

  - name: Check if AWS cli is installed
    shell: |
      aws --version
    register: aws_cli_installed
    ignore_errors: yes

  - name: Print aws_cli version if installed
    debug:
      msg: "AWS cli {{ aws_cli_installed.stdout }} version is already installed."
    when: aws_cli_installed.rc == 0

  - name: Install required packages for AWS CLI
    become: yes
    become_user: root
    apt:
      name: 
        - unzip
    when: aws_cli_installed.rc != 0 and ansible_os_family == "Debian"

  - name: Download AWS CLI package
    get_url:
      url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
      dest: "/home/{{ ansible_user }}/awscliv2.zip"
    when: aws_cli_installed.rc != 0

  - name: Wait for AWS CLI package to be downloaded
    wait_for:
      path: "/home/{{ ansible_user }}/awscliv2.zip"
      state: present
    when: aws_cli_installed.rc != 0

  - name: Unzip AWS CLI package
    unarchive:
      src: "/home/{{ ansible_user }}/awscliv2.zip"
      dest: "/home/{{ ansible_user }}"
      remote_src: yes
      creates: "/home/{{ ansible_user }}/aws"
    when: aws_cli_installed.rc != 0

  - name: Wait for AWS CLI package to be downloaded
    wait_for:
      path: "/home/{{ ansible_user }}/aws"
      state: present
    when: aws_cli_installed.rc != 0

  - name: Run AWS CLI installer
    become: yes
    become_user: root
    shell: |
      "/home/{{ ansible_user }}/aws/install"
    when: aws_cli_installed.rc != 0

  - name: Wait for AWS CLI installation to finish
    shell: |
      aws --version
    register: aws_cli_new_installed
    until: aws_cli_new_installed.rc == 0
    retries: 60  # Adjust the number of retries as needed
    delay: 5     # Delay between retries
    when: aws_cli_installed.rc != 0

  - name: Clean up downloaded files
    file:
      path: "/home/{{ ansible_user }}/{{ item }}"
      state: absent
    loop:
      - awscliv2.zip
      - aws
    when: aws_cli_installed.rc != 0