- name: Install Ansible
  gather_facts: true
  collections:
    - community.general
  hosts: "{{ host_group }}"

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    playbook_file_path: "{{ (lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ')).split() | select('match','^.*[.]ya?ml$') | list | first }}"
    playbook_file_name: "{{ playbook_file_path | basename }}"

  tasks:

    - name: Check if Ansible is installed
      shell: |
        ansible --version
      register: ansible_installed
      ignore_errors: yes

    - name: Print ansible version if installed
      debug:
        msg: "{{ ansible_installed.stdout }} version is already installed."
      when: ansible_installed.rc == 0

    - name: Install ansible
      become: yes
      become_user: root
      apt:
        name: ansible
      when: ansible_installed.rc != 0 and ansible_os_family == "Debian"

    - name: Install ansible (for Red Hat/CentOS)
      become: yes
      become_user: root
      yum:
        name: ansible
      when: ansible_installed.rc != 0 and ansible_os_family == "RedHat"

    - name: Install ansible (for Amazon Linux)
      become: yes
      become_user: root
      yum:
        name: ansible
      when: ansible_installed.rc != 0 and ansible_distribution == "Amazon"

    # Wait for ansible installation to finish
    - name: Wait for AWS installation to finish
      shell: |
        ansible --version
      register: ansible_new_installed
      until: ansible_new_installed.rc == 0
      retries: 60  # Adjust the number of retries as needed
      delay: 5     # Delay between retries
      when: ansible_installed.rc != 0