- name: Do Required Woking for Local
  gather_facts: true
  hosts: local

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    playbook_file_path: "{{ (lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ')).split() | select('match','^.*[.]ya?ml$') | list | first }}"
    playbook_dir_path: "{{ playbook_file_path | dirname }}"
    playbook_file_name: "{{ playbook_file_path | basename }}"

  tasks:

    - name: Install pip
      become: true
      become_user: root
      apt:
        name: python3-pip
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Pip (for RedHat/CentOS)
      become: true
      become_user: root
      yum:
        name: python3-pip
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install Jinja2
      become: true
      become_user: root
      pip:
        name: Jinja2
        executable: pip3

    - name: Create kubernetes cluster configuration file with template
      shell: |
        python "{{ playbook_dir_path }}/../../{{ KOPS_TPL_RENDERER_PY_FILE }}" \
              "{{ playbook_dir_path }}/../../{{ KOPS_TPL_J2_FILE }}" \
              "{{ playbook_dir_path }}/../../{{ KOPS_TPL_VALUE_JSON_FILE }}" \
              "{{ playbook_dir_path }}/../../{{ KOPS_CONF_YAML_FILE }}"

    - name: Read and print the contents of the YAML file
      include_vars:
        file: "{{ playbook_dir_path }}/../../{{ KOPS_CONF_YAML_FILE }}"
      register: kOPS_cluster_configuratin_file_contents

    - name: Print the contents of the YAML file
      debug:
        var: kOPS_cluster_configuratin_file_contents