- name: Send ansible configuration file
  gather_facts: false
  hosts: "{{ host_group }}"

  tasks:

    - name: Create ansible configuration directory
      file:
        path: "{{ ANSIBLE_DIR }}"
        state: directory

    - name: Copy ansible configuration file to remote hosts
      copy:
        src: "{{ ANSIBLE_CONF_FILE }}"
        dest: "{{ ANSIBLE_DIR }}/{{ ANSIBLE_CONF_FILE_NAME }}"
        owner: "{{ ansible_user }}"  # Optional: Set the owner of the file
        group: "{{ ansible_user }}"  # Optional: Set the group of the file
        mode: 0644  # Optional: Set the permissions of the file

    - name: Copy ansible hosts file to remote hosts
      copy:
        src: "{{ ANSIBLE_HOSTS_FILE }}"
        dest: "{{ ANSIBLE_DIR }}/{{ ANSIBLE_HOSTS_FILE_NAME }}"
        owner: "{{ ansible_user }}"  # Optional: Set the owner of the file
        group: "{{ ansible_user }}"  # Optional: Set the group of the file
        mode: 0644  # Optional: Set the permissions of the file