- name: Install ArgoCD via Helm with NGINX Ingress 
  gather_facts: true
  hosts: "{{ host_group }}"

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  environment:
      AWS_PAGER: ""
      AWS_PROFILE: "{{ AWS_PROFILE }}"  # Set your desired AWS profile here
      KOPS_CLUSTER_NAME: "{{ KOPS_CLUSTER_NAME }}"
      KOPS_STATE_STORE: "{{ KOPS_STATE_S3 }}"

  tasks:

    - name: Copy files to remote host
      copy:
        src: "{{ item }}"
        dest: "{{ KOPS_DIR }}/"
        owner: "{{ ansible_user }}"  # Optional: Set the owner of the file
        group: "{{ ansible_user }}"  # Optional: Set the group of the file
        mode: 0644  # Optional: Set the permissions of the file
      with_fileglob:
        - "{{ K8S_MANIFEST_DIR }}/*"
      delegate_to: localhost

    # - name: Copy files to remote host
    #   copy:
    #     src: "{{ item.path }}"
    #     dest: "{{ KOPS_DIR }}/"
    #     owner: "{{ ansible_user }}"  # Optional: Set the owner of the file
    #     group: "{{ ansible_user }}"  # Optional: Set the group of the file
    #     mode: 0644  # Optional: Set the permissions of the file
    #   loop: "{{ files_to_copy.files }}"
    #   loop_control:
    #     label: "{{ item.path }}"
    #   delegate_to: localhost

    # - name: Apply Namespace YAML Files
    #   kubernetes.core.k8s:
    #     state: present
    #     src: "{{ KOPS_DIR }}/03.cluster_namespace_manifest.yaml"

    # - name: Add Helm repo for NGINX Ingress Controller
    #   kubernetes.core.helm_repository:
    #     name: bitnami
    #     repo_url: "https://charts.bitnami.com/bitnami"
    #     state: present

    # - name: Install NGINX Ingress Controller Helm chart
    #   kubernetes.core.helm:
    #     release_name: nginx-ingress
    #     chart_ref: bitnami/nginx-ingress-controller
    #     wait: yes
    #     namespace: nginx-ingress-controller  # or the appropriate namespace
    #     values_files:
    #       - "{{ KOPS_DIR }}/04.helm_value_aws_alb_ingress_controller.yaml"
    #     state: present
        
    # - name: Add Helm repo for ArgoCD
    #   kubernetes.core.helm_repository:
    #     name: argo-cd
    #     repo_url: "https://argoproj.github.io/argo-helm"
    #     state: present

    # - name: Install ArgoCD Helm chart
    #   kubernetes.core.helm:
    #     release_name: argocd
    #     chart_ref: argo-cd/argo-cd
    #     wait: yes
    #     namespace: argocd  # Set the desired namespace
    #     values_files:
    #       - "{{ KOPS_DIR }}/05.helm_value_argocd.yaml"
    #     state: present
    #     ##