- name: Install ArgoCD via Helm with NGINX Ingress 
  gather_facts: true
  hosts: "{{ host_group }}"

  environment:
      AWS_PAGER: ""
      AWS_PROFILE: "{{ AWS_PROFILE }}"  # Set your desired AWS profile here
      KOPS_CLUSTER_NAME: "{{ KOPS_CLUSTER_NAME }}"
      KOPS_STATE_STORE: "{{ KOPS_STATE_S3 }}"

  vars:
    argocd_domain: argocd.calife.co.kr  # Replace with your domain
    helm_chart_url: "https://charts.bitnami.com/bitnami"

  tasks:
  
    - name: Add Helm repo for NGINX Ingress Controller
      community.kubernetes.helm_repository:
        name: bitnami
        repo_url: "{{ helm_chart_url }}"
        state: present

    - name: Install NGINX Ingress Controller Helm chart
      community.kubernetes.helm:
        release_name: nginx-ingress
        chart_ref: bitnami/nginx-ingress-controller
        namespace: default  # or the appropriate namespace
        state: present

    - name: Create ArgoCD Ingress
      community.kubernetes.k8s:
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: argocd-server-ingress
            namespace: argocd
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/rewrite-target: /
          spec:
            rules:
              - host: "{{ argocd_domain }}"
                http:
                  paths:
                    - pathType: Prefix
                      path: /
                      backend:
                        service:
                          name: argocd-server
                          port:
                            number: 80
