name: Set Secrets

on:
  push:
    branches:
      - master

jobs:

  set-secret:
    runs-on: ubuntu-latest
    
    env:
      INFRA_GIT_REPO_OWNER: "CAL-REPO"
      INFRA_GIT_REPO_NAME: "CAL-INFRA"
      INFRA_GIT_REPO_TOKEN: ${{ secrets.CAL_SC_INFRA_GIT_REPO_MASTER_TOKEN }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          path: master

      - name: Set cloudflare email and apikey from secret to github action environment variable
        working-directory: master/2.WORKFLOWS_SCRIPT
        env:
          CLOUDFLARE_CSV_DATA: ${{ secrets.CAL_SC_CSV_CLOUDFLARE_ENCODED }}
          GIT_OWNER: ${{ env.INFRA_GIT_REPO_OWNER }}
          GIT_REPO: ${{ env.INFRA_GIT_REPO_NAME }}
          GH_TOKEN: ${{ env.INFRA_GIT_REPO_TOKEN }}
        run: |
          bash "set_cloudflare_profile_with_csv_data_to_gh_repo_secret.sh"

      - name: Set github repository from secret to github action environment variable
        working-directory: master/2.WORKFLOWS_SCRIPT
        env:
          GIT_PROFILE_CSV_DATA: ${{ secrets.CAL_SC_CSV_GIT_REPO_PROFILE_ENCODED }}
          GIT_OWNER: ${{ env.INFRA_GIT_REPO_OWNER }}
          GIT_REPO: ${{ env.INFRA_GIT_REPO_NAME }}
          GH_TOKEN: ${{ env.INFRA_GIT_REPO_TOKEN }}
        run: |
          bash "set_git_auth_url_with_csv_data_to_gh_repo_secret.sh"