name: Execute Master Workflow

on:
  push:
    branches:
      - deploy  # Replace with the appropriate branch name

jobs:

  trigger-master-workflows:
    runs-on: ubuntu-latest

    env:
      GIT_REPO_OWNER: "CAL-REPO"
      GIT_REPO_NAME: "CAL-INFRA"
      GIT_REPO_BRANCH: "master"
      GIT_WORKFLOW_DEPLOY_NAME: "Deploy Infrastructure"
      GIT_WORKFLOW_DELETE_NAME: "Delete Infrastructure"
      GIT_WORKFLOW_CONDITION: "deploy"

    steps:

      - name: Determine Workflow to Trigger
        id: decide
        run: |
          if [[ ${{ env.GIT_WORKFLOW_CONDITION }} == "deploy" ]]; then
            echo "Deploy workflow"
            echo "::set-output name=${{ env.GIT_WORKFLOW_DEPLOY_NAME }}::deploy-workflow"  # Use the actual workflow name in the Master Workflows repository
          else
            echo "Delete workflow"
            echo "::set-output name=${{ env.GIT_WORKFLOW_DELETE_NAME }}::delete-workflow"  # Use the actual workflow name in the Master Workflows repository
        shell: bash

      - name: Trigger Appropriate Workflow on Master Workflows Repository
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workflowToTrigger = `${{ steps.decide.outputs.workflow }}`;
            const response = await octokit.actions.createWorkflowDispatch({
              owner: ${{ env.GIT_REPO_OWNER }},
              repo: ${{ env.GIT_REPO_NAME }},
              workflow_id: workflowToTrigger,
              ref: ${{ env.GIT_REPO_BRANCH }}  # Use the appropriate branch name
            });
            console.log(`Triggered ${workflowToTrigger} in Master Workflows repository`);